package com.wanderwildwood.ibasho.ui.settings

import android.app.job.JobScheduler

fun Int.pendingJobReasonToString(): String {
    return when (this) {
        JobScheduler.PENDING_JOB_REASON_INVALID_JOB_ID -> "INVALID_JOB_ID"
        JobScheduler.PENDING_JOB_REASON_EXECUTING -> "EXECUTING"
        JobScheduler.PENDING_JOB_REASON_UNDEFINED -> "UNDEFINED"
        JobScheduler.PENDING_JOB_REASON_APP -> "APP"
        JobScheduler.PENDING_JOB_REASON_APP_STANDBY -> "APP_STANDBY"
        JobScheduler.PENDING_JOB_REASON_BACKGROUND_RESTRICTION -> "BACKGROUND_RESTRICTION"
        JobScheduler.PENDING_JOB_REASON_CONSTRAINT_BATTERY_NOT_LOW -> "CONSTRAINT_BATTERY_NOT_LOW"
        JobScheduler.PENDING_JOB_REASON_CONSTRAINT_CHARGING -> "CONSTRAINT_CHARGING"
        JobScheduler.PENDING_JOB_REASON_CONSTRAINT_CONNECTIVITY -> "CONSTRAINT_CONNECTIVITY"
        JobScheduler.PENDING_JOB_REASON_CONSTRAINT_CONTENT_TRIGGER -> "CONSTRAINT_CONTENT_TRIGGER"
        JobScheduler.PENDING_JOB_REASON_CONSTRAINT_DEVICE_IDLE -> "CONSTRAINT_DEVICE_IDLE"
        JobScheduler.PENDING_JOB_REASON_CONSTRAINT_MINIMUM_LATENCY -> "CONSTRAINT_MINIMUM_LATENCY"
        JobScheduler.PENDING_JOB_REASON_CONSTRAINT_PREFETCH -> "CONSTRAINT_PREFETCH"
        JobScheduler.PENDING_JOB_REASON_CONSTRAINT_STORAGE_NOT_LOW -> "CONSTRAINT_STORAGE_NOT_LOW"
        JobScheduler.PENDING_JOB_REASON_DEVICE_STATE -> "DEVICE_STATE"
        JobScheduler.PENDING_JOB_REASON_JOB_SCHEDULER_OPTIMIZATION -> "JOB_SCHEDULER_OPTIMIZATION"
        JobScheduler.PENDING_JOB_REASON_QUOTA -> "QUOTA"
        JobScheduler.PENDING_JOB_REASON_USER -> "USER"
        else -> "??(${this})??"
    }
}
